version: '3.8'

services:
  # Flink JobManager
  flink-jobmanager:
    image: flink:1.17.1-scala_2.12-java11
    hostname: flink-jobmanager
    container_name: flink-jobmanager
    ports:
      - "8082:8081"
    command: jobmanager
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: flink-jobmanager"
    volumes:
      - flink-checkpoints:/tmp/flink-checkpoints
      - flink-savepoints:/tmp/flink-savepoints
    networks:
      - flink-network

  # Flink TaskManager
  flink-taskmanager:
    image: flink:1.17.1-scala_2.12-java11
    hostname: flink-taskmanager
    container_name: flink-taskmanager
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: flink-jobmanager\ntaskmanager.numberOfTaskSlots: 2"
    volumes:
      - flink-checkpoints:/tmp/flink-checkpoints
      - flink-savepoints:/tmp/flink-savepoints
    networks:
      - flink-network

  # PyFlink Anomaly Detection Job
  pyflink-anomaly-detector:
    build: .
    container_name: pyflink-anomaly-detector
    depends_on:
      - flink-jobmanager
      - flink-taskmanager
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:9092
      - FLINK_JOBMANAGER_ADDRESS=flink-jobmanager:8081
    volumes:
      - ./:/app
    networks:
      - flink-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  flink-checkpoints:
  flink-savepoints:

networks:
  flink-network:
    driver: bridge